[project]
name = "game-deal-notifier-tools"
version = "0.1.0"
description = "For local development"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff~=0.14",
    "pre-commit~=4.5",
    "mypy~=1.19",
    "ipython~=9.8",
]
