name: Mypy

on: [ push, pull_request ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      telegram_bot: ${{ steps.filter.outputs.telegram_bot }}
      rest_api: ${{ steps.filter.outputs.rest_api }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            telegram_bot:
              - 'telegram_bot/**'
            rest_api:
              - 'rest_api/**'

  mypy-telegram-bot:
    runs-on: ubuntu-latest
    if: needs.changes.outputs.telegram_bot == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          pyproject-file: 'telegram_bot/pyproject.toml'

      - name: Mypy
        working-directory: telegram_bot
        run: uv run --frozen mypy .

  mypy-rest-api:
    runs-on: ubuntu-latest
    if: needs.changes.outputs.rest_api == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          pyproject-file: 'rest_api/pyproject.toml'

      - name: Mypy
        working-directory: rest_api
        run: uv run --frozen mypy .
