name: Mypy

on: [ push, pull_request ]

jobs:
  mypy-telegram-bot:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' && github.event.head_commit && (
        contains(join(github.event.head_commit.added, '\n'), 'telegram_bot/') ||
        contains(join(github.event.head_commit.modified, '\n'), 'telegram_bot/') ||
        contains(join(github.event.head_commit.removed, '\n'), 'telegram_bot/')
      ) ||
      github.event_name == 'pull_request' && (
        contains(join(github.event.pull_request.changed_files, '\n'), 'telegram_bot/')
      )
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          pyproject-file: 'telegram_bot/pyproject.toml'

      - name: Mypy
        working-directory: telegram_bot
        run: uv run --frozen mypy .

  mypy-rest-api:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' && github.event.head_commit && (
        contains(join(github.event.head_commit.added, '\n'), 'rest_api/') ||
        contains(join(github.event.head_commit.modified, '\n'), 'rest_api/') ||
        contains(join(github.event.head_commit.removed, '\n'), 'rest_api/')
      ) ||
      github.event_name == 'pull_request' && (
        contains(join(github.event.pull_request.changed_files, '\n'), 'rest_api/')
      )
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          pyproject-file: 'rest_api/pyproject.toml'

      - name: Mypy
        working-directory: rest_api
        run: uv run --frozen mypy .
