name: Ruff
on: [ push, pull_request ]
jobs:
  ruff-telegram-bot:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' && github.event.head_commit && (
        contains(join(github.event.head_commit.added, '\n'), 'telegram_bot/') ||
        contains(join(github.event.head_commit.modified, '\n'), 'telegram_bot/') ||
        contains(join(github.event.head_commit.removed, '\n'), 'telegram_bot/')
      ) ||
      github.event_name == 'pull_request' && (
        contains(join(github.event.pull_request.changed_files, '\n'), 'telegram_bot/')
      )
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: 'telegram_bot'
          version-file: 'telegram_bot/pyproject.toml'

  ruff-rest-api:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' && github.event.head_commit && (
        contains(join(github.event.head_commit.added, '\n'), 'rest_api/') ||
        contains(join(github.event.head_commit.modified, '\n'), 'rest_api/') ||
        contains(join(github.event.head_commit.removed, '\n'), 'rest_api/')
      ) ||
      github.event_name == 'pull_request' && (
        contains(join(github.event.pull_request.changed_files, '\n'), 'rest_api/')
      )
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: 'rest_api'
          version-file: 'rest_api/pyproject.toml'
