name: Ruff
on: [ push, pull_request ]
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      telegram_bot: ${{ steps.filter.outputs.telegram_bot }}
      rest_api: ${{ steps.filter.outputs.rest_api }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            telegram_bot:
              - 'telegram_bot/**'
            rest_api:
              - 'rest_api/**'
  ruff-telegram-bot:
    runs-on: ubuntu-latest
    if: needs.changes.outputs.telegram_bot == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: 'telegram_bot'
          version-file: 'telegram_bot/pyproject.toml'

  ruff-rest-api:
    runs-on: ubuntu-latest
    if: needs.changes.outputs.rest_api == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: 'rest_api'
          version-file: 'rest_api/pyproject.toml'
